In [113]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action="ignore")

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mpl
mpl.rcParams["axes.unicode_minus"] = False

import tensorflow as tf

## 1. 정의

+ 시계열의 데이터와 같이 시간의 흐름에 따라 변화하는 데이터를 학습하기 위한 딥러닝 모델
+ 기준 기점 t와 다음 시점 t+1 네트워크를 연결하여 구성한 인공신경망

# 2. 의의

+ "그는 그녀에게 빨간 사과의 의미로 빨간사과 한바구니를 건내주며 미안하다 했다"

+ 위의 문장과 같이 단순한 사전적인 의미 뿐만 아니라, 앞뒤 문장의 요소들을 종합적으로 판단하여 의미를 파악하고 해석

## 3. 자연어 처리(NLP)

+ Thesaurus : 유의어 사전
     - 시대 변화에 대응하기가 어렵다
     - 단어의 미묘한 차이를 표현하기 어렵다
     
+ 통계 기반 기법
     - 어떤 단어가 주목했을 때 그 주변에 어떤 단어가 몇번 등장 하는지 세어 보는 기법
     - 거대 행렬 발생
     

+ 추론 기반 기법 :  WordVec

## 4.  두 가지 결과

+ 다중분류
    - 품사 분류
                i google at work
                i work at google 
                이두개를 어떻게 분류하는가...? 순서?!
                대명사 동사 전치사 명사.... 
                출력선이 2개다.... 
                
                
                
+ 이진분류 1아니면 0 
    - 감정 분석 (화났느냐 화가안났느냐)
                traffic ticket fines
                traffic is fine
                



## 5. 종류


+ 4개의 회로를 통해 I WORK AT GOOGLE 이렇게 넘어온다
+ WHH 히든스테이지에서 넘어온값이다...
+ Vanilla RNN
+ LSTM

## 6. 실습(Vanilla RNN)

#### (1) 단일 cell을 통한 계산 처리과정 : 기본 사용법

In [114]:
###### 입력 데이터 : 1행 2열

inputs = np.array([[[1,2]]])

In [95]:
import warnings
warnings.filterwarnings(action="ignore")

tf.reset_default_graph()
tf.set_random_seed(777)

tf_inputs = tf.constant(inputs,dtype=tf.float32)


##### 출력데이터 : 2행 3열

rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=3) # 3개를 출력하겠다. 
outputs, state =tf.nn.dynamic_rnn(cell=rnn_cell, dtype=tf.float32, inputs=tf_inputs) # 넘겨준다 # 다른값과 달리 2개이다. 
                                                                    # 위옆으로 나감
    

print(outputs)
print(state)

print("\n Weights")
for w in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
    print(w)
    
    
    
print("-----------------------------------------------------------------------")


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outputs_run, state_run = sess.run([outputs, state])
    
    print("output values")
    print(outputs_run)
    
    print("\nstate values")
    print(state_run)
    
    print("\nWeights")
    variable_names = [v.name for v in tf.trainable_variables()]
    values = sess.run(variable_names)
    for k,v in zip(variable_names,values):
        print(k,v)

Tensor("rnn/transpose_1:0", shape=(1, 1, 3), dtype=float32)
Tensor("rnn/while/Exit_3:0", shape=(1, 3), dtype=float32)

 Weights
<tf.Variable 'rnn/basic_rnn_cell/kernel:0' shape=(5, 3) dtype=float32_ref>
<tf.Variable 'rnn/basic_rnn_cell/bias:0' shape=(3,) dtype=float32_ref>
-----------------------------------------------------------------------
output values
[[[-0.9314169   0.75578666 -0.6819246 ]]]

state values
[[-0.9314169   0.75578666 -0.6819246 ]]

Weights
rnn/basic_rnn_cell/kernel:0 [[-0.62831575  0.38538355  0.79733914]
 [-0.5203329   0.30046564 -0.8150209 ]
 [ 0.39399797  0.16670114  0.4062907 ]
 [-0.6391754   0.8460203   0.5266966 ]
 [ 0.41124135  0.66347724 -0.0210759 ]]
rnn/basic_rnn_cell/bias:0 [0. 0. 0.]


# (2) 다중 cell 사용

In [96]:
# I work at google = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]

# I google at work = [[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]]


inputs = np.array([
    [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],
    [[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]]    
])



In [97]:
import warnings
warnings.filterwarnings(action="ignore")

tf.reset_default_graph()
tf.set_random_seed(777)

tf_inputs = tf.constant(inputs, dtype=tf.float32)

##### 출력 데이터 
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=3)
outputs, state = tf.nn.dynamic_rnn(cell=rnn_cell, dtype=tf.float32, inputs=tf_inputs)

print(outputs)
print("----------------------------------------------------")
print(state)
print("----------------------------------------------------")

print("\n Weights")
for w in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
    print(w)

Tensor("rnn/transpose_1:0", shape=(2, 4, 3), dtype=float32)
----------------------------------------------------
Tensor("rnn/while/Exit_3:0", shape=(2, 3), dtype=float32)
----------------------------------------------------

 Weights
<tf.Variable 'rnn/basic_rnn_cell/kernel:0' shape=(7, 3) dtype=float32_ref>
<tf.Variable 'rnn/basic_rnn_cell/bias:0' shape=(3,) dtype=float32_ref>


In [98]:

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outputs_run, state_run = sess.run([outputs, state])
    
    print("output values")
    print(outputs_run)
    
    print("\nstate values")
    print(state_run)
    
    print("\nWeights")
    variable_names = [v.name for v in tf.trainable_variables()]
    values = sess.run(variable_names)
    for k,v in zip(variable_names,values):
        print(k,v)
        
        
        
# 위로 옆으로 위로 옆으로 위로 옆으로 위로 옆으로 4개가 나감 출력값 4줄
# 첫번째 출력값은 같음.

output values
[[[-0.50944704  0.33166462  0.6126557 ]
  [-0.20793891  0.24406303 -0.75278705]
  [-0.06346128 -0.52844936  0.68356085]
  [-0.36491966  0.8857268  -0.02324395]]

 [[-0.50944704  0.33166462  0.6126557 ]
  [-0.30707452  0.62735885  0.21719742]
  [ 0.5043804  -0.14038289  0.3744523 ]
  [-0.11641277  0.70696247 -0.7512605 ]]]

state values
[[-0.36491966  0.8857268  -0.02324395]
 [-0.11641277  0.70696247 -0.7512605 ]]

Weights
rnn/basic_rnn_cell/kernel:0 [[-0.56198275  0.34469748  0.7131618 ]
 [-0.4653999   0.2687447  -0.7289769 ]
 [ 0.35240245  0.14910203  0.36339748]
 [-0.57169586  0.7567036   0.47109187]
 [ 0.3678255   0.5934322  -0.01885086]
 [ 0.31208777 -0.40880746  0.22867584]
 [ 0.5521256   0.682691   -0.5481483 ]]
rnn/basic_rnn_cell/bias:0 [0. 0. 0.]


In [99]:

tf.reset_default_graph()

idx2char = ['h', 'i', 'e', 'l', 'o']

x_one_hot = [[
    [1, 0, 0, 0, 0],  # h 0
    [0, 1, 0, 0, 0],  # i 1
    [1, 0, 0, 0, 0],  # h 0
    [0, 0, 1, 0, 0],  # e 2
    [0, 0, 0, 1, 0],  # l 3
    [0, 0, 0, 1, 0]   # l 3
]]

y_data = [[1, 0, 2, 3, 3, 4]] 


#6행 5열 [[]] 2차원 데이터가 1개

In [100]:
##### parameter
sequence_len = 6
num_classes = 5


In [101]:

##### 입출력 준비
tf.reset_default_graph()

X = tf.placeholder(tf.float32, shape=[None, sequence_len, num_classes]) # 6행 5열
y = tf.placeholder(tf.int32, shape=[None, sequence_len])

In [102]:
##### rnn 모델
cell = tf.contrib.rnn.BasicRNNCell(num_units=num_classes)
outputs, state = tf.nn.dynamic_rnn(cell=cell, inputs=X, dtype=tf.float32)
print(outputs) #6행 5열
print(state) # 5열

Tensor("rnn/transpose_1:0", shape=(?, 6, 5), dtype=float32)
Tensor("rnn/while/Exit_3:0", shape=(?, 5), dtype=float32)


In [103]:
#### 평면화(Flat Layer)


X_for_fc = tf.reshape(outputs, [-1, num_classes]) # 3차원에서 2차원으로 바뀜
print(X_for_fc)

Tensor("Reshape:0", shape=(?, 5), dtype=float32)


In [104]:


##### FC Layer 
outputs = tf.contrib.layers.fully_connected(inputs=X_for_fc, num_outputs=10, activation_fn=None)
outputs = tf.contrib.layers.fully_connected(inputs=outputs, num_outputs=num_classes, activation_fn=None)
#print(outputs)
#print(outputs)2차원 평면화 작업해서


# 다시 비용할때는 3차원으로 해줘야함
outputs = tf.reshape(outputs, [1, sequence_len, num_classes])
W = tf.ones([1, sequence_len])
cost = tf.reduce_mean(tf.contrib.seq2seq.sequence_loss(logits=outputs, targets=y, weights=W))
train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(cost)

In [105]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(10):
        _, c = sess.run([train, cost], feed_dict={X:x_one_hot, y:y_data})
        preds = sess.run(tf.argmax(outputs, 2), feed_dict={X:x_one_hot})
        print(i, c, "예측값 : ", preds, "  정답 : ", y_data)
        
    result = [idx2char[c] for c in np.squeeze(preds)]
    print("결과 : ", ",".join(result))

0 1.5636729 예측값 :  [[2 4 2 4 4 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
1 1.1384872 예측값 :  [[2 0 2 3 3 3]]   정답 :  [[1, 0, 2, 3, 3, 4]]
2 0.79422253 예측값 :  [[2 0 2 3 3 3]]   정답 :  [[1, 0, 2, 3, 3, 4]]
3 0.48125294 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
4 0.30325094 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
5 0.17139758 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
6 0.0785101 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
7 0.03323372 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
8 0.014068037 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
9 0.0057669324 예측값 :  [[1 0 2 3 3 4]]   정답 :  [[1, 0, 2, 3, 3, 4]]
결과 :  i,h,e,l,l,o


In [121]:
# sample = "You will have to submit to your fate wheather you will or not"
sample = "You will have to"

idx2char = list(set(sample))
print(idx2char)

char2idx = {c:i for i,c in enumerate(idx2char)}
print(char2idx)

sample_idx = [char2idx [c] for c in sample]
print(sample)

X_data = [sample_idx[:-1]]
y_data = [sample_idx[1:]]


import warnings
warnings.filterwarnings(action="ignore")

['u', 'w', 'i', 'h', 'o', 'e', 'v', 'Y', ' ', 'l', 'a', 't']
{'u': 0, 'w': 1, 'i': 2, 'h': 3, 'o': 4, 'e': 5, 'v': 6, 'Y': 7, ' ': 8, 'l': 9, 'a': 10, 't': 11}
You will have to


In [127]:
#### parameter

sequence_len = len(sample) -1
num_classes = len(idx2char)

In [128]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, shape=[None, sequence_len])

y=  tf.placeholder(tf.int32, shape=[None, sequence_len])

x_one_hot = tf.one_hot(X,num_classes)
x_one_hot

<tf.Tensor 'one_hot:0' shape=(?, 15, 12) dtype=float32>

In [129]:
cell =tf.contrib.rnn.BasicRNNCell(num_units =num_classes)
outputs,state = tf.nn.dynamic_rnn(cell=cell,inputs=x_one_hot, dtype=tf.float32)
print(outputs)
print(state)

Tensor("rnn/transpose_1:0", shape=(?, 15, 12), dtype=float32)
Tensor("rnn/while/Exit_3:0", shape=(?, 12), dtype=float32)


In [130]:
W = tf.ones([1,sequence_len])
cost = tf.reduce_mean(tf.contrib.seq2seq.sequence_loss(logits=outputs, targets=y, weights=W))
train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

In [131]:

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(1001):
        _,c = sess.run([train,cost], feed_dict={X:X_data, y:y_data})
        preds = sess.run(tf.argmax(outputs,2), feed_dict={X:X_data})
        
        if i%100 == 0:
            print(i, "cost", c)
           # print("예측값:", preds)
           # print("정답", y_data)
            print("------------------------------")
            
    result = [idx2char[c] for c in np.squeeze(preds)]
    print("결과:", ',' .join(result))

0 cost 2.4687846
------------------------------
100 cost 1.1364002
------------------------------
200 cost 1.0081258
------------------------------
300 cost 0.9751041
------------------------------
400 cost 0.96119964
------------------------------
500 cost 0.9534926
------------------------------
600 cost 0.948429
------------------------------
700 cost 0.94474167
------------------------------
800 cost 0.9418789
------------------------------
900 cost 0.939567
------------------------------
1000 cost 0.93765223
------------------------------
결과: o,u, ,w,i,l,l, ,h,a,v,e, ,t,o


## 7. LSTM(Long Short Term Memory)

+ BPTT : Back propagation Through Time
    - Gradient Vanishing
    - Gradient Exploding
    
    
    # sigmoid 에 기존의 기억을 저장시키고
    # 후에 추가를 시킨다.
    

In [41]:
tf.reset_default_graph()
tf.set_random_seed(777)

inputs = np.array([[[1,0]]])

tf_inputs = tf.constant(inputs,dtype=tf.float32)
cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=1)
outputs, states=tf.nn.dynamic_rnn(cell=cell, dtype=tf.float32, inputs= tf_inputs)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outputs_run, states_run = sess.run([outputs,states])
    
    print(outputs_run)
    print(states_run.h)
    print(states_run.c)


[[[0.09927537]]]
[[0.09927537]]
[[0.18134572]]


### (1) 실습1

In [43]:
#### 데이터 준비


paragraph_dict_list = [
         {'paragraph': 'dishplace is located in sunnyvale downtown there is parking around the area but it can be difficult to find during peak business hours my sisters and i came to this place for dinner on a weekday they were really busy so i highly recommended making reservations unless you have the patience to wait', 'category': 'food'},
         {'paragraph': 'service can be slower during busy hours but our waiter was courteous and help gave some great entree recommendations', 'category': 'food'},
         {'paragraph': 'portions are huge both french toast and their various omelettes are really good their french toast is probably 1.5x more than other brunch places great place to visit if you are hungry and dont want to wait 1 hour for a table', 'category': 'food'},
         {'paragraph': 'we started with apps going the chicken and waffle slides and chicken nachos the sliders were amazing and the nachos were good too maybe by themselves the nachos would have scored better but after those sliders they were up against some tough competition', 'category': 'food'},
         {'paragraph': 'the biscuits and gravy was too salty two people in my group had the gravy and all thought it was too salty my hubby ordered a side of double egg and it was served on two small plates who serves eggs to one person on separate plates we commented on that when it was delivered and even the server laughed and said she doesnt know why the kitchen does that presentation of food is important and they really missed on this one', 'category': 'food'},
         {'paragraph': 'the garlic fries were a great starter (and a happy hour special) the pancakes looked and tasted great and were a fairly generous portion', 'category': 'food'},
         {'paragraph': 'our meal was excellent i had the pasta ai formaggi which was so rich i didnt dare eat it all although i certainly wanted to excellent flavors with a great texture contrast between the soft pasta and the crisp bread crumbs too much sauce for me but a wonderful dish', 'category': 'food'},
         {'paragraph': 'what i enjoy most about palo alto is so many restaurants have dog-friendly seating outside i had bookmarked italico from when they first opened about a 1.5 years ago and was jonesing for some pasta so time to finally knock that bookmark off', 'category': 'food'},
         {'paragraph': 'the drinks came out fairly quickly a good two to three minutes after the orders were taken i expected my iced tea to taste a bit more sweet but this was straight up green tea with ice in it not to complain of course but i was pleasantly surprised', 'category': 'food'},
         {'paragraph': 'despite the not so good burger the service was so slow the restaurant wasnt even half full and they took very long from the moment we got seated to the time we left it was almost 2 hours we thought that it would be quick since we ordered as soon as we sat down my coworkers did seem to enjoy their beef burgers for those who eat beef however i will not be returning it is too expensive and extremely slow service', 'category': 'food'},
    
         {'paragraph': 'the four reigning major champions simona halep caroline wozniacki angelique kerber and defending us open champion sloane stephens could make a case for being the quartet most likely to succeed especially as all but stephens has also enjoyed the no1 ranking within the last 14 months as they prepare for their gruelling new york campaigns they currently hold the top four places in the ranks', 'category': 'sports'},
         {'paragraph': 'the briton was seeded nn7 here last year before a slump in form and confidence took her down to no46 after five first-round losses but there have been signs of a turnaround including a victory over a sub-par serena williams in san jose plus wins against jelena ostapenko and victoria azarenka in montreal. konta pulled out of new haven this week with illness but will hope for good things where she first scored wins in a major before her big breakthroughs to the semis in australia and wimbledon', 'category': 'sports'},
         {'paragraph': 'stephens surged her way back from injury in stunning style to win her first major here last year—and ranked just no83 she has since proved what a big time player she is winning the miami title via four fellow major champions then reaching the final at the french open back on north american hard courts she ran to the final in montreal only just edged out by halep she has also avoided many of the big names in her quarter—except for wild card azarenka as a possible in the third round', 'category': 'sports'},
         {'paragraph': 'when it came to england chances in the world cup it would be fair to say that most fans had never been more pessimistic than they were this year after enduring years of truly dismal performances at major tournaments – culminating in the 2014 event where they failed to win any of their three group games and finished in bottom spot those results led to the resignation of manager roy hodgson', 'category': 'sports'},
         {'paragraph': 'the team that eliminated russia – croatia – also improved enormously during the tournament before it began their odds were 33/1 but they played with real flair and star players like luka modric ivan rakitic and ivan perisic showed their quality on the world stage having displayed their potential by winning all three of their group stage games croatia went on to face difficult tests like the semi-final against england', 'category': 'sports'},
         {'paragraph': 'the perseyside outfit finished in fourth place in the premier league table and without a trophy last term after having reached the champions league final before losing to real madrid', 'category': 'sports'},
         {'paragraph': 'liverpool fc will return to premier league action on saturday lunchtime when they travel to leicester city in the top flight as they look to make it four wins in a row in the league', 'category': 'sports'},
         {'paragraph': 'alisson signed for liverpool fc from as roma this summer and the brazilian goalkeeper has helped the reds to keep three clean sheets in their first three premier league games', 'category': 'sports'},
         {'paragraph': 'but the rankings during that run-in to new york hid some very different undercurrents for murray had struggled with a hip injury since the clay swing and had not played a match since losing his quarter-final at wimbledon and he would pull out of the us open just two days before the tournament began—too late however to promote nederer to the no2 seeding', 'category': 'sports'},
         {'paragraph': 'then came the oh-so-familiar djokovic-nadal no-quarter-given battle for dominance in the thiadal more than once pulled off a reverse smash and had his chance to seal the tie-break but it was djokovic serving at 10-9 who dragged one decisive error from nadal for a two-sets lead', 'category': 'sports'}
]


df = pd.DataFrame(paragraph_dict_list)
df = df[["paragraph","category" ]]

df

paragraph category
0   dishplace is located in sunnyvale downtown the...     food
1   service can be slower during busy hours but ou...     food
2   portions are huge both french toast and their ...     food
3   we started with apps going the chicken and waf...     food
4   the biscuits and gravy was too salty two peopl...     food
5   the garlic fries were a great starter (and a h...     food
6   our meal was excellent i had the pasta ai form...     food
7   what i enjoy most about palo alto is so many r...     food
8   the drinks came out fairly quickly a good two ...     food
9   despite the not so good burger the service was...     food
10  the four reigning major champions simona halep...   sports
11  the briton was seeded nn7 here last year befor...   sports
12  stephens surged her way back from injury in st...   sports
13  when it came to england chances in the world c...   sports
14  the team that eliminated russia – croatia – al...   sports
15  the perseyside outfit finished in fourth place...   sports
16  liverpool fc will return to premier league act...   sports
17  alisson signed for liverpool fc from as roma t...   sports
18  but the rankings during that run-in to new yor...   sports
19  then came the oh-so-familiar djokovic-nadal no...   sports

## 1) Preprocessing

In [52]:


##### 단어를 분리한 뒤 중복된 단어를 제거
word_list = []

for data in df["paragraph"]:
    word_list.append(data.split(" "))
    
word = []
for i in word_list:
    for j in i:
        word.append(j)
        
print(len(set(word)))
print(word)


530
['dishplace', 'is', 'located', 'in', 'sunnyvale', 'downtown', 'there', 'is', 'parking', 'around', 'the', 'area', 'but', 'it', 'can', 'be', 'difficult', 'to', 'find', 'during', 'peak', 'business', 'hours', 'my', 'sisters', 'and', 'i', 'came', 'to', 'this', 'place', 'for', 'dinner', 'on', 'a', 'weekday', 'they', 'were', 'really', 'busy', 'so', 'i', 'highly', 'recommended', 'making', 'reservations', 'unless', 'you', 'have', 'the', 'patience', 'to', 'wait', 'service', 'can', 'be', 'slower', 'during', 'busy', 'hours', 'but', 'our', 'waiter', 'was', 'courteous', 'and', 'help', 'gave', 'some', 'great', 'entree', 'recommendations', 'portions', 'are', 'huge', 'both', 'french', 'toast', 'and', 'their', 'various', 'omelettes', 'are', 'really', 'good', 'their', 'french', 'toast', 'is', 'probably', '1.5x', 'more', 'than', 'other', 'brunch', 'places', 'great', 'place', 'to', 'visit', 'if', 'you', 'are', 'hungry', 'and', 'dont', 'want', 'to', 'wait', '1', 'hour', 'for', 'a', 'table', 'we', 'start

In [54]:
results =set()
df["paragraph"].str.lower().str.split().apply(results.update)
len(results)

# lower소문자 spilt 으로 공백으로 뽑아줌

530

In [69]:
# 단어와 숫자를 매핑해서 dict 자료형 변수 작성(idx2word)

idx2word = dict(enumerate(results))
print(idx2word[470])
print(idx2word[3])

dishplace
1.5


In [58]:
word2idx = {word:num for word, num in zip(results, range(len(results)))}
word2idx 

{'city': 0,
 'with': 1,
 'ai': 2,
 '1.5': 3,
 'losses': 4,
 'lunchtime': 5,
 'outfit': 6,
 'sub-par': 7,
 'great': 8,
 'my': 9,
 'unless': 10,
 'patience': 11,
 'garlic': 12,
 'jonesing': 13,
 'huge': 14,
 'taste': 15,
 'dismal': 16,
 'burgers': 17,
 'stunning': 18,
 'wozniacki': 19,
 'nadal': 20,
 'quickly': 21,
 'taken': 22,
 'win': 23,
 'probably': 24,
 'oh-so-familiar': 25,
 'starter': 26,
 'slides': 27,
 'culminating': 28,
 'results': 29,
 'montreal.': 30,
 'players': 31,
 'toast': 32,
 'seating': 33,
 'struggled': 34,
 'missed': 35,
 'ordered': 36,
 'green': 37,
 'their': 38,
 'premier': 39,
 'once': 40,
 'clean': 41,
 'first': 42,
 'crumbs': 43,
 'winning': 44,
 'keep': 45,
 'edged': 46,
 'ranked': 47,
 'places': 48,
 'much': 49,
 'year': 50,
 'generous': 51,
 'injury': 52,
 'failed': 53,
 'north': 54,
 'no-quarter-given': 55,
 '2': 56,
 'course': 57,
 'for': 58,
 'way': 59,
 'served': 60,
 'enjoyed': 61,
 'no1': 62,
 'too': 63,
 'iced': 64,
 'where': 65,
 'pull': 66,
 'top': 67

In [59]:
word2idx ={v:k for k,v in idx2word.items()}

In [74]:
#### 데이터드을 숫자로 변환

def encoded_paragraph(param):
    words = param.split()
    encoded =[]
    
    for w in words:
        encoded.append([word2idx[w]])
        
    return encoded 

def encoded_category(param) :
    if param == "food":
        return[1,0]
    else:
        return[0,1]
    
# 각 문장에서 단어의 갯수 파악

def word_cnt(param):
    return len(param.split())

In [75]:
df["enc_paragraph"] = df.paragraph.apply(encoded_paragraph)
df.head()

paragraph category  \
0  dishplace is located in sunnyvale downtown the...     food   
1  service can be slower during busy hours but ou...     food   
2  portions are huge both french toast and their ...     food   
3  we started with apps going the chicken and waf...     food   
4  the biscuits and gravy was too salty two peopl...     food   

                                       enc_paragraph enc_category  
0  [[470], [179], [219], [304], [91], [360], [144...       [1, 0]  
1  [[445], [505], [443], [205], [238], [417], [35...       [1, 0]  
2  [[446], [525], [14], [258], [524], [32], [322]...       [1, 0]  
3  [[303], [368], [1], [335], [246], [373], [191]...       [1, 0]  
4  [[373], [284], [322], [129], [146], [63], [336...       [1, 0]

In [76]:
df["enc_category"] = df.category.apply(encoded_category)
df.head()

paragraph category  \
0  dishplace is located in sunnyvale downtown the...     food   
1  service can be slower during busy hours but ou...     food   
2  portions are huge both french toast and their ...     food   
3  we started with apps going the chicken and waf...     food   
4  the biscuits and gravy was too salty two peopl...     food   

                                       enc_paragraph enc_category  
0  [[470], [179], [219], [304], [91], [360], [144...       [1, 0]  
1  [[445], [505], [443], [205], [238], [417], [35...       [1, 0]  
2  [[446], [525], [14], [258], [524], [32], [322]...       [1, 0]  
3  [[303], [368], [1], [335], [246], [373], [191]...       [1, 0]  
4  [[373], [284], [322], [129], [146], [63], [336...       [1, 0]

In [78]:
df["seq_length"] = df.paragraph.apply(word_cnt)
df.head(50)

paragraph category  \
0   dishplace is located in sunnyvale downtown the...     food   
1   service can be slower during busy hours but ou...     food   
2   portions are huge both french toast and their ...     food   
3   we started with apps going the chicken and waf...     food   
4   the biscuits and gravy was too salty two peopl...     food   
5   the garlic fries were a great starter (and a h...     food   
6   our meal was excellent i had the pasta ai form...     food   
7   what i enjoy most about palo alto is so many r...     food   
8   the drinks came out fairly quickly a good two ...     food   
9   despite the not so good burger the service was...     food   
10  the four reigning major champions simona halep...   sports   
11  the briton was seeded nn7 here last year befor...   sports   
12  stephens surged her way back from injury in st...   sports   
13  when it came to england chances in the world c...   sports   
14  the team that eliminated russia – croatia – al...   sports   
15  the perseyside outfit finished in fourth place...   sports   
16  liverpool fc will return to premier league act...   sports   
17  alisson signed for liverpool fc from as roma t...   sports   
18  but the rankings during that run-in to new yor...   sports   
19  then came the oh-so-familiar djokovic-nadal no...   sports   

                                        enc_paragraph enc_category  seq_length  
0   [[470], [179], [219], [304], [91], [360], [144...       [1, 0]          53  
1   [[445], [505], [443], [205], [238], [417], [35...       [1, 0]          19  
2   [[446], [525], [14], [258], [524], [32], [322]...       [1, 0]          42  
3   [[303], [368], [1], [335], [246], [373], [191]...       [1, 0]          43  
4   [[373], [284], [322], [129], [146], [63], [336...       [1, 0]          82  
5   [[373], [12], [480], [457], [380], [8], [26], ...       [1, 0]          24  
6   [[92], [267], [146], [138], [519], [327], [373...       [1, 0]          50  
7   [[415], [519], [362], [198], [316], [204], [24...       [1, 0]          43  
8   [[373], [233], [187], [318], [169], [21], [380...       [1, 0]          49  
9   [[290], [373], [128], [178], [96], [406], [373...       [1, 0]          82  
10  [[373], [196], [103], [448], [363], [110], [48...       [0, 1]          65  
11  [[373], [333], [146], [319], [382], [484], [51...       [0, 1]          88  
12  [[497], [192], [117], [59], [162], [263], [52]...       [0, 1]          91  
13  [[84], [252], [187], [477], [248], [395], [304...       [0, 1]          71  
14  [[373], [116], [495], [308], [184], [423], [76...       [0, 1]          70  
15  [[373], [100], [6], [440], [304], [386], [529]...       [0, 1]          30  
16  [[372], [278], [300], [392], [477], [39], [481...       [0, 1]          35  
17  [[262], [126], [58], [372], [278], [263], [72]...       [0, 1]          30  
18  [[136], [373], [353], [238], [495], [467], [47...       [0, 1]          63  
19  [[109], [187], [373], [25], [428], [55], [331]...       [0, 1]          46

In [79]:
### 문장의 최대 길이

max_word_cnt = 0 

for row in df["paragraph"]:
    if len(row.split()) > max_word_cnt:
        max_word_cnt = len(row.split())
        
        
print(max_word_cnt)
        

91


In [81]:
max_word_cnt = df['seq_length'].max()
max_word_cnt 

91

In [83]:
#### 문장의 길이가 91개가 안될 경우 -1로 채운다.

def sequence_padding(enc_param):
    seq_len = len(enc_param)
    
    for i in range(seq_len,max_word_cnt):
        enc_param.append([-1])
        
    return enc_param

In [84]:
df["enc_paragraph"] = df.enc_paragraph.apply(sequence_padding)

In [85]:
print(df["enc_paragraph"][0])

[[470], [179], [219], [304], [91], [360], [144], [179], [222], [69], [373], [501], [136], [252], [505], [443], [464], [477], [492], [238], [212], [367], [355], [9], [154], [322], [519], [187], [477], [435], [529], [58], [369], [241], [380], [526], [251], [457], [147], [417], [178], [519], [400], [80], [510], [102], [10], [472], [444], [373], [11], [477], [153], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1]]


In [86]:
#### 입력 값들은 배열로 변환

enc_paragraph = np.array(df.enc_paragraph.tolist())
enc_category = np.array(df.enc_category.tolist())
seq_length = np.array(df.seq_length.tolist())

### 2) 모델 구축

In [88]:
train_X = enc_paragraph
train_y = enc_category

print(train_X.shape, train_y.shape)

(20, 91, 1) (20, 2)


In [92]:
tf.reset_default_graph()
tf.set_random_seed(777)

# parameter

lr = 0.001

n_epochs =300

X = tf.placeholder(tf.float32,[None,max_word_cnt,1])
y = tf.placeholder(tf.int32, [None,2])

cell = tf.nn.rnn_cell.LSTMCell(num_units=64) #출력갯수
outputs, states = tf.nn.dynamic_rnn(cell=cell, inputs=X,dtype=tf.float32,
                                    sequence_length = seq_length)

#print(outputs)
#print(states)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [107]:
### FC Layer

#W1 =tf.Variable(tf.random_normal([64, 32])) #64개를 입력받고 32를 출력받음
#b1 =tf.Variable(tf.random_normal([32]))
#layer1 = tf.nn.relu(tf.matmul(state.h, W1) +b1)
layer1 = tf.layers.dense(states.h,32)               

#W2 = tf.Variable(tf.random_normal([32, 2])) #64개를 입력받고 32를 출력받음
#b2 = tf.Variable(tf.random_normal([2]))
#logit = tf.matmul(layer1, W2)+ b2
 
logit = tf.layers.dense(layer1,2)
    
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logit, labels=y))
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)
                
print(layer1)
print(logit)



# keras 끝판왕

Instructions for updating:
Use keras.layers.Dense instead.
Instructions for updating:
Please use `layer.__call__` method instead.
Tensor("dense/BiasAdd:0", shape=(?, 32), dtype=float32)
Tensor("dense_1/BiasAdd:0", shape=(?, 2), dtype=float32)


In [101]:
?tf.layers.Dense

In [112]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(n_epochs):
        _,c = sess.run([train,cost],feed_dict={X:train_X,y:train_y})
        
        if epoch %50 == 0:
            preds =tf.nn.softmax(logit)
            correct_pred = tf.equal(tf.argmax(preds,1),tf.argmax(y,1))
            accuracy = tf.reduce_mean(tf.cast(correct_pred,"float"))
            cur_acc = accuracy.eval({X:train_X, y:train_y})
            print(epoch,":",c,",",cur_acc)

0 : 0.92600346 , 0.5
50 : 0.422928 , 0.85
100 : 0.07359274 , 1.0
150 : 0.0032911059 , 1.0
200 : 0.0007719825 , 1.0
250 : 0.00022704285 , 1.0
